spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/orders
spring.datasource.username=admin
spring.datasource.password=P@ssw0rd123!

spring.jpa.hibernate.ddl-auto=update

external.api.key=sample-api-key
external.api.base-url=http://localhost:8080/mock-api
