spring.application.name=order-service

spring.config.import=vault://

spring.cloud.vault.uri=${VAULT_URI:http://127.0.0.1:8200}
spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=${VAULT_TOKEN}

spring.cloud.vault.database.enabled=true
spring.cloud.vault.database.backend=database
spring.cloud.vault.database.role=order-service-role
spring.cloud.vault.database.username-property=spring.datasource.username
spring.cloud.vault.database.password-property=spring.datasource.password

spring.datasource.url=jdbc:postgresql://localhost:5432/orders

spring.jpa.hibernate.ddl-auto=update

external.api.base-url=http://localhost:8080/mock-api